### ISSUE TITLE
Effect size and sampling variance bug?

### ISSUE THREAD

**Issue by tressoldi** [kylehamilton/JamoviMeta#5]
It seems there is a bug related to the "Effects size and sampling variance" option.
See this screenshot

![jamovimeta](https://user-images.githubusercontent.com/11275642/29078448-bea7bf56-7c5a-11e7-80b6-7e5862b0c9d6.JPG)

**Comment by kylehamilton** [comment]
ooo good eye! I was about to check this before pushing it to the repo but I got sidetracked with a draft of my thesis. I'll take care of this today. Thanks for catching this!

**Comment by tressoldi** [comment]
Hi Kyle, any news about this bug?

**Comment by SCgeeker** [comment]
Wish this bug fixed as soon as you can. I am writing a brief article how to conduct the meta-analysis for the open data.

**Comment by kylehamilton** [comment]
Opss sorry school started and I got swamped! I'll make the fix tomorrow, promise this time!

**Comment by kylehamilton** [comment]
Ok I think everything is working now. Let me know if you find any problems. I've included an example dataset in this last push. It's all fake data and was done for fun. ![image](https://user-images.githubusercontent.com/2274317/30236357-b6dc5b6c-94cc-11e7-8dd2-e7a8e86854ff.png)

**Comment by tressoldi** [comment]
Fixed.
Thank you very much.
